### PR TITLE
Fix Table Component Scroll & Light Mode Color Issues

### LINKED ISSUE #460: Bug Report: Table Component Scroll & Light Mode Color Issues
### 1. **Light mode color not applied**  
   Some UI elements do not reflect the light mode color scheme correctly.  

| | Light Mode | Dark Mode |
|---|------------|-----------|
| **Preview** | Light Mode | Dark Mode |
| **Notes** | Some elements do not switch to light mode colors. | Colors applied correctly. |

</br>

### 2. **Table not scrollable on mobile**  
   In mobile or narrow screen views, the table component cannot be scrolled horizontally.  

| **Content** |
|-------------|
| Mobile Table Scroll |
| Mobile Table Scroll Issue |
| Table cannot be scrolled horizontally. |

### PR DESCRIPTION
**Pull request by arty0928**
> Resolves #460

</br>

## Problem 1: Table not horizontally scrollable on mobile devices

The props table in component documentation pages was not horizontally scrollable on mobile devices, causing content to be cut off when the table width exceeded the viewport width.

### Root Cause

The `Table` component wrapper had `overflow="hidden"`, which prevented horizontal scrolling:
```tsx
// apps/landing/src/components/mdx/components/Table/index.tsx
export const Table = ({ ...props }: ComponentProps<'table'>) => {
  return (
    <Box borderRadius="0.5rem" overflow="hidden">  // Blocked scrolling
      <Box {...props} as="table" borderCollapse="collapse" borderSpacing={0} />
    </Box>
  )
}
```

### Solution

1. Added scroll container to `PropsTable` with `overflow="auto"` and set minimum table width
2. Changed Table wrapper `overflow` from `hidden` to `visible`
```tsx
// apps/landing/src/components/PropsTable.tsx
<Box maxWidth="100%" overflow="auto" width="100%">
  <Table border={0} style={{ minWidth: '600px' }}>
```
```tsx
// apps/landing/src/components/mdx/components/Table/index.tsx
<Box borderRadius="0.5rem" overflow="visible">  //  hidden → visible
```

**Files modified:**
- `apps/landing/src/components/PropsTable.tsx`
- `apps/landing/src/components/mdx/components/Table/index.tsx`

### Result

| Before | After |
|--------|-------|
| image | image |
| ❌ Table content cut off | ✅ Horizontal scroll enabled |

</br>

## Problem 2: Inline code not visible in light mode

Inline code (backtick-wrapped) was not visible in light mode due to insufficient contrast between background and text colors.

| Light Mode (Before) | Dark Mode (Before) |
|---------------------|---------------------|
| image | image |
| ❌ Code barely visible | ✅ Works correctly |

### Root Cause

`CustomCodeBlock` component used `$containerBackground` which was `#FFF` in light mode, providing no contrast with the surrounding content.

### Solution

Added dedicated `codeBackground` color token to avoid affecting other components:
- Light mode: `#F5F5F5` 
- Dark mode: `#2E2E2E`
```tsx
// CustomCodeBlock.tsx
<Box bg="$codeBackground">  // Changed from $containerBackground
```

**Files modified:**
- `apps/landing/devup.json`
- `packages/components/devup.json`
- `apps/landing/src/components/mdx/components/CustomCodeBlock.tsx`

### Result

| Light Mode (After) | Dark Mode (After) |
|--------------------|---------------------|
| image | image |
| ✅ Code now visible with proper contrast | ✅ Maintains correct appearance |

### CODE REVIEW

File: apps/landing/src/components/mdx/components/Table/index.tsx [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { type ComponentProps } from 'react'
 
 export const Table = ({ ...props }: ComponentProps<'table'>) => {
   return (
-    <Box borderRadius="0.5rem" overflow="hidden">
+    <Box borderRadius="0.5rem" overflow="visible">
```
Comment (owjs3901) [inline apps/landing/src/components/mdx/components/Table/index.tsx]: The default value of overflow is set visible.
So this is unnecessary

File: apps/landing/src/components/PropsTable.tsx [hunk 2]
```diff
@@ -41,50 +41,52 @@ export const PropsTable = async (props: PropTableProps) => {
...
+                <Text>No props to display</Text>
               </TableCell>
-              <TableCell>
-                <MdxComponentsWithCodeBlock>
-                  {description}
-                </MdxComponentsWithCodeBlock>
-              </TableCell>
-              <TableCell>
-                <VStack>
+            </TableRow>
```
Comment (owjs3901) [inline apps/landing/src/components/PropsTable.tsx]: Very Good

File: apps/landing/src/components/mdx/components/Table/index.tsx (hunk 1 above)
Comment (arty0928) [reply apps/landing/src/components/mdx/components/Table/index.tsx]: there was an issue **when using the table component inside an MDX file.**
The parent element was wrapped with a Box component that had overflow: hidden applied, which prevented the child table component’s overflow behavior from working properly.
To fix this, we had to change the overflow value from hidden to visible when using the table inside an MDX file.
In fact, if it remains set to hidden, horizontal scrolling on the table does not work correctly.
